import { OutputFormat, ModelOption } from '@/types';

export const OUTPUT_FORMATS: OutputFormat[] = [
    // ─── SOCIAL MEDIA ───
    {
        id: 'ig-post',
        label: 'Instagram Photo Post',
        category: 'social',
        type: 'image',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'ig-story',
        label: 'Instagram Story / Reel Cover',
        category: 'social',
        type: 'image',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'ig-reel',
        label: 'Instagram Reel (video)',
        category: 'social',
        type: 'video',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        duration: '5–8s',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 50,
    },
    {
        id: 'fb-post',
        label: 'Facebook Photo Post',
        category: 'social',
        type: 'image',
        width: 1200,
        height: 630,
        aspectRatio: '1.91:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'fb-story',
        label: 'Facebook Story',
        category: 'social',
        type: 'image',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'pinterest',
        label: 'Pinterest Pin',
        category: 'social',
        type: 'image',
        width: 1000,
        height: 1500,
        aspectRatio: '2:3',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'twitter-banner',
        label: 'Twitter / X Banner',
        category: 'social',
        type: 'image',
        width: 1500,
        height: 500,
        aspectRatio: '3:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },

    // ─── PAID ADS ───
    {
        id: 'meta-feed-ad',
        label: 'Meta Feed Ad (Photo)',
        category: 'ads',
        type: 'image',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        notes: 'Keep text under 20% of image',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'meta-story-ad',
        label: 'Meta Story Ad',
        category: 'ads',
        type: 'image',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'meta-video-ad',
        label: 'Meta Video Ad',
        category: 'ads',
        type: 'video',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        duration: '5–15s',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 80,
    },
    {
        id: 'meta-carousel',
        label: 'Meta Carousel Ad',
        category: 'ads',
        type: 'image',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        notes: 'Generate 3–5 cards per batch',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'google-display-rect',
        label: 'Google Display (Large Rectangle)',
        category: 'ads',
        type: 'image',
        width: 336,
        height: 280,
        aspectRatio: '6:5',
        recommendedModel: 'imagen-3.0-fast-generate-001',
        creditEstimate: 5,
    },
    {
        id: 'google-display-leader',
        label: 'Google Display (Leaderboard)',
        category: 'ads',
        type: 'image',
        width: 728,
        height: 90,
        aspectRatio: '8:1',
        recommendedModel: 'imagen-3.0-fast-generate-001',
        creditEstimate: 5,
    },
    {
        id: 'reddit-feed-ad',
        label: 'Reddit Feed Ad',
        category: 'ads',
        type: 'image',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'reddit-mobile-ad',
        label: 'Reddit Mobile Ad',
        category: 'ads',
        type: 'image',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'tiktok-video-ad',
        label: 'TikTok Video Ad',
        category: 'ads',
        type: 'video',
        width: 1080,
        height: 1920,
        aspectRatio: '9:16',
        duration: '9–15s',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 80,
    },
    {
        id: 'youtube-preroll',
        label: 'YouTube Pre-roll Ad',
        category: 'ads',
        type: 'video',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        duration: '6–15s',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 80,
    },

    // ─── WEBSITE ───
    {
        id: 'web-hero-desktop',
        label: 'Website Hero (Desktop)',
        category: 'website',
        type: 'image',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'web-hero-mobile',
        label: 'Website Hero (Mobile)',
        category: 'website',
        type: 'image',
        width: 828,
        height: 1792,
        aspectRatio: '9:19',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'web-hero-video-desktop',
        label: 'Website Hero Video (Desktop)',
        category: 'website',
        type: 'video',
        width: 1920,
        height: 1080,
        aspectRatio: '16:9',
        duration: '10–30s loop',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 120,
    },
    {
        id: 'web-hero-video-mobile',
        label: 'Website Hero Video (Mobile)',
        category: 'website',
        type: 'video',
        width: 828,
        height: 1792,
        aspectRatio: '9:16',
        duration: '10–30s loop',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 120,
    },
    {
        id: 'web-section-bg',
        label: 'Website Section Background',
        category: 'website',
        type: 'image',
        width: 1440,
        height: 900,
        aspectRatio: '16:10',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'web-feature-card',
        label: 'Feature Card Image',
        category: 'website',
        type: 'image',
        width: 800,
        height: 600,
        aspectRatio: '4:3',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'blog-header',
        label: 'Blog Header',
        category: 'website',
        type: 'image',
        width: 1200,
        height: 628,
        aspectRatio: '1.91:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },

    // ─── SHOPIFY / E-COMMERCE ───
    {
        id: 'shopify-product',
        label: 'Shopify Product Image',
        category: 'shopify',
        type: 'image',
        width: 2048,
        height: 2048,
        aspectRatio: '1:1',
        notes: 'Clean studio white background',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'shopify-lifestyle',
        label: 'Shopify Lifestyle Image',
        category: 'shopify',
        type: 'image',
        width: 2048,
        height: 2048,
        aspectRatio: '1:1',
        notes: 'Contextual/lifestyle setting',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'shopify-hero-banner',
        label: 'Shopify Hero Banner',
        category: 'shopify',
        type: 'image',
        width: 2048,
        height: 683,
        aspectRatio: '3:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'shopify-collection',
        label: 'Shopify Collection Banner',
        category: 'shopify',
        type: 'image',
        width: 1200,
        height: 400,
        aspectRatio: '3:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'shopify-product-video',
        label: 'Shopify Product Video',
        category: 'shopify',
        type: 'video',
        width: 1080,
        height: 1080,
        aspectRatio: '1:1',
        duration: '10–30s',
        recommendedModel: 'veo-2.0-generate-001',
        creditEstimate: 100,
    },
    {
        id: 'amazon-product',
        label: 'Amazon Product Main',
        category: 'shopify',
        type: 'image',
        width: 2000,
        height: 2000,
        aspectRatio: '1:1',
        notes: 'Pure white background required',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
    {
        id: 'amazon-lifestyle',
        label: 'Amazon Lifestyle A+',
        category: 'shopify',
        type: 'image',
        width: 1464,
        height: 600,
        aspectRatio: '2.44:1',
        recommendedModel: 'imagen-3.0-generate-002',
        creditEstimate: 10,
    },
];

export const MODEL_OPTIONS: ModelOption[] = [
    {
        id: 'imagen-3-standard',
        name: 'Imagen 3',
        provider: 'google',
        type: 'image',
        tier: 'free',
        quality: 'balanced',
        description: 'Google\'s latest stable image model. Excellent photorealism, great for product shots and lifestyle.',
        bestFor: ['Product photos', 'Social posts', 'Website heroes', 'Ads'],
        creditCost: 'Free tier: ~100 images/day',
        apiModel: 'imagen-3.0-generate-002',
    },
    {
        id: 'imagen-3-fast',
        name: 'Imagen 3 Fast',
        provider: 'google',
        type: 'image',
        tier: 'free',
        quality: 'fast',
        description: 'Faster, lighter version. Great for rapid iteration and drafts. Lower quality but quick.',
        bestFor: ['Quick drafts', 'Bulk generation', 'Iteration'],
        creditCost: 'Free tier: ~200 images/day',
        apiModel: 'imagen-3.0-fast-generate-001',
    },
    {
        id: 'gemini-flash-image',
        name: 'Gemini 2.0 Flash (Image)',
        provider: 'google',
        type: 'image',
        tier: 'free',
        quality: 'balanced',
        description: 'Gemini\'s built-in image generation. Good for text-in-image and complex compositional prompts.',
        bestFor: ['Text overlays', 'Complex scenes', 'Prompt following'],
        creditCost: 'Free tier: generous daily quota',
        apiModel: 'gemini-2.0-flash-exp',
    },
    {
        id: 'veo-2',
        name: 'Veo 2',
        provider: 'google',
        type: 'video',
        tier: 'paid',
        quality: 'ultra',
        description: 'Google\'s cinematic video model. Generates 5–8s HD clips from text or image prompts.',
        bestFor: ['Instagram Reels', 'Hero videos', 'Product demos', 'Ads'],
        creditCost: '~$0.35/sec (use Cloud credit)',
        apiModel: 'veo-2.0-generate-001',
    },
    {
        id: 'gemini-flash-enhance',
        name: 'Gemini 2.0 Flash (Enhance)',
        provider: 'google',
        type: 'text',
        tier: 'free',
        quality: 'fast',
        description: 'Used to enhance your prompts and analyze reference images. Runs automatically.',
        bestFor: ['Prompt enhancement', 'Reference analysis', 'Style extraction'],
        creditCost: 'Free tier: very generous',
        apiModel: 'gemini-2.0-flash',
    },
];

export const CATEGORY_LABELS: Record<string, string> = {
    social: '📱 Social Media',
    ads: '🎯 Paid Ads',
    website: '🌐 Website',
    shopify: '🛍️ Shopify / E-Commerce',
};
